resolvers:
    - 1.1.1.1
    - 1.0.0.1
sources:
    - alienvault
    - binaryedge
    - bufferover
    - certspotter
    - certspotterold
    - censys
    - chaos
    - crtsh
    - dnsdumpster
    - hackertarget
    - intelx
    - ipv4info
    - passivetotal
    - securitytrails
    - shodan
    - spyse
    - sublist3r
    - threatcrowd
    - threatminer
    - virustotal
all-sources:
    - alienvault
    - archiveis
    - binaryedge
    - bufferover
    - censys
    - certspotter
    - certspotterold
    - chaos
    - commoncrawl
    - crtsh
    - dnsdumpster
    - dnsdb
    - entrust
    - github
    - hackertarget
    - ipv4info
    - intelx
    - passivetotal
    - rapiddns
    - recon
    - securitytrails
    - shodan
    - sitedossier
    - spyse
    - sublist3r
    - threatcrowd
    - threatminer
    - virustotal
    - waybackarchive
    - zoomeye
recursive:
    - alienvault
    - bufferover
    - certspotter
    - certspotterold
    - crtsh
    - dnsdumpster
    - hackertarget
    - ipv4info
    - passivetotal
    - securitytrails
    - sublist3r
    - virustotal
binaryedge: []
censys:
    - 54482de1-2820-453a-bff6-84a3b8de66ba:c0sNqrB0J3nI90f2hB7bzSq2KGD9cWKu
certspotter: []
chaos: []
dnsdb: []
github:
    - 7bbc77dae130bec43001df7c31a95e6c7ad4e8bd
    - ec7672ce7e928e275b4c867a765d203185a12157
intelx: []
passivetotal: []
securitytrails: []
shodan:
    - pIOlZD13g2UiblhGGyaOR2cqMwstOaZB
spyse: []
urlscan: []
virustotal: []
zoomeye: []
subfinder-version: 2.4.1
